[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68080ecf9a6bd9910949c2369b6255f796040967"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "9ef2d76084ea527d9b7d8162781530860ae3edab8da554e45ced1514705420f9"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.3+0/VideoCaptureWrap.v0.1.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8439233f88f1174d4351ef15e13d0b4e5943bf7"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "d6d8f41ad395abe8cf209b4f0bbbda0275ba66a3634880b4327f7302aed6a514"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.3+0/VideoCaptureWrap.v0.1.3.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63de7ef1dcbab3fac5b00046dc08ff5cd328c82a"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "97caa772ac3e3150ddd6bd28aa72661aebb9236d16e90724b69963b6883d49ee"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.3+0/VideoCaptureWrap.v0.1.3.x86_64-w64-mingw32-cxx11.tar.gz"
