[[VideoCaptureWrap]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95fa6d4c90b16e82eda114b07c6a8660d29f838f"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "99c3b09d6c73d5830651bc5b8208d7b96bd1f71cba6e12d6ef7b1f117635ccc8"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.1+0/VideoCaptureWrap.v0.4.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
git-tree-sha1 = "52476f71b07988aeac2858091d50e329903d3f94"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "e6b6fb1897927eab37bc49bbabba13f82acee3e8be348feecc467db702462c01"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.2+0/VideoCaptureWrap.v0.4.2.armv7l-linux-gnueabihf.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0b30b90650d91356c9026176bcc1505f9f911d6"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "2f0dd87a72b3ca6898f3ddec26c915da9db778fd95335a154afd56ad3cad2e7c"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.2+0/VideoCaptureWrap.v0.4.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "870ea67ef3f40a3de868c43e9b297801dc9b8f78"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "dfaa92633313022f34f24225fefb2f67760027baddae041543311a69ae35b9a4"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.2+0/VideoCaptureWrap.v0.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78cf7ce598ffed5ab09f099ac890f561d488e3c0"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "fc4860f79b53abaeec8865949107056f24dbe13c4937813fe6f3b7a6b3c55d06"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.2+0/VideoCaptureWrap.v0.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
