[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8637e03c1a434ffe8733d6cf9ffd17625dad8698"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "057b7f67886b57b25e3d0046f2b6e7d78919fdf5b7223ccffd5cf1e3a3817f36"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.6+0/VideoCaptureWrap.v0.1.6.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "405fdd3a98586fa9aa86e91a9218d056efd6304b"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "07f2fe35e062a9376fdc4fe63a0c526c024ff1fae7823d0cce3eac5964a0bbcc"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.6+0/VideoCaptureWrap.v0.1.6.x86_64-w64-mingw32-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d784ef1962fd21b6be8ac5d08e386723b609ce9a"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "00da25054c8f5ab9f40b76911e54f770751f95a99d2322bb3e57a2f511fa4394"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.2.0+0/VideoCaptureWrap.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
