[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ca1ffd2723816db8317fff5769797149c9d8d4d"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "660feaf275584f09bb2298529e3cea11e48e05d51c5d8d1d50a7e3a906cf0165"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.3.1+0/VideoCaptureWrap.v0.3.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b51f0c65ac38307eba582d012ad19ee612d2db45"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "54e17117cb9b36e94d8bca969966873fd8494d445e92f3d94588df5122e5837d"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.3.1+0/VideoCaptureWrap.v0.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "542baf711dbc66d00a07d59a1bd48ce352c868d1"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "10949bb9e726c08040838df120b8cf9bbfe2e46c5bdcbedb062cff7eb386005d"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.3.1+0/VideoCaptureWrap.v0.3.1.x86_64-w64-mingw32-cxx11.tar.gz"
