[[VideoCaptureWrap]]
arch = "armv7l"
git-tree-sha1 = "52476f71b07988aeac2858091d50e329903d3f94"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "e6b6fb1897927eab37bc49bbabba13f82acee3e8be348feecc467db702462c01"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.2+0/VideoCaptureWrap.v0.4.2.armv7l-linux-gnueabihf.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf76fe30e38a9462e5aeeb78e6eb5d1d0d2d909f"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "bc71fba3bc2ec54805d47b58a9411abf099bcafc15751ecd82c2ce51a9174b3f"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.8.0+0/VideoCaptureWrap.v0.8.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9579fff63ac2d5fce96af4c4842ad822678be6a"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "a01345f75ed2bf09dcf3f332c31dc39109d99266621e0b157e49ef28a37f7578"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.8.0+0/VideoCaptureWrap.v0.8.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b00d5a0453bc1e004467ab238d75f7c57500949"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "da27302315234bdb7b48b7e813ebec181993d522082f340acf5b8da3054d8e5c"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.aarch64-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43a5ac743d08f8d75c549e71f8889e6bbd48b6c1"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "12e2127bb29b07a51758093897bacf58f122dc3cec3213208f4a092f8ba0964b"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3dc23c62d9dca49da9f1c02f4717b5f05179d15d"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "2592c24cc5caf376d71d698551d30972f89c335f822223c38c728b283d3687e1"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.aarch64-linux-musl-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54a83e260207f8fa0991385019b9bf2b93095205"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "d9a0c082019d6d943605fa0353689c0b17df1df6782e32f3ab6597f24cdcfda6"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b2ddae02c43b3200e7dcd5b7cc19887831eebe1"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "3fa681dfb37361c068d59e964bc95c82c38c2d63c8c769bf1d92a59ad1420b75"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5884b7282d0f9edf834d9279c0e9efd8511b5e39"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "87d6bb4fcab39200a3c79714a67b09ea70742080e292bc3b1f99e0f83300b9e3"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d897316a5df2dc78dcdd4d6c999202cda915841"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "dcc2c7a4f86ff1f382d05fa95d950c8acbb85a26823cebdf29539fb5a41f28c8"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af40c92702bacf1893f3f208c8840a55922fc3dd"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "5d58747e74b3fbe099816ada59334313bac56211013df9ca6aa84bc8a6e2e89f"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da82e0591b23ddd064fed7c173eae9bba5062701"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "e70ca41a7ce7b5ecb9d5f0f926a072d9a3f5c7f60dd993a87ced1dcdabcb19e3"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.i686-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22b027fb2a0444902090921483c30bb1683246e1"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "67c6801a42d79fa14dff420baf69121670517df48bc347161ed2e5e3d97da725"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.i686-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f260b56600867ae7e47addb800d339cd49e800b"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "85c61cedf6bc79b785b4a6207e2193f548a46c8b54efddd7651f209bff7f8b8b"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.i686-w64-mingw32-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55580772e8cfcec53813eed1d1d1056309356de9"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "9127e67a368aaaeb107a89497b274667eebd9f0392febd39dc8c41d0db50caf0"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.i686-w64-mingw32-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
git-tree-sha1 = "ef572ae21ac69e05ed96a914c0351de6a35c6e87"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "88e761935cd915c4d4c19149a90e789b6d2b5f1bd2a5390e15391bcaae676371"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.x86_64-apple-darwin.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d623073c6bb06234adcb64031842d8efc9b85289"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "bb2dfecd94b4218bffb465b198fdea17fb27048bd154f9e71b47628d90242c96"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.x86_64-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60fe9305d34a9a2038c1bd8100087426060f3f96"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "75966f99f796ac4a1f1ac9efb9d124cbb8437b9cbce0f826edb6ed80b964ee1f"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "971196e07a1cde530ebdb76ad6fdf52efb6be65a"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "a6478d649e58be8b957e09539178add5d9be45c635d6f26f82eb32f2732a4347"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1955be01cd78c243c79e8057e0e94ee09f99df7f"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "f4622b328a9942d88397c1608f860ad3712f1b043197a8e8d08936296bbe81e1"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
