[[VideoCaptureWrap]]
arch = "armv7l"
git-tree-sha1 = "52476f71b07988aeac2858091d50e329903d3f94"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "e6b6fb1897927eab37bc49bbabba13f82acee3e8be348feecc467db702462c01"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.2+0/VideoCaptureWrap.v0.4.2.armv7l-linux-gnueabihf.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf76fe30e38a9462e5aeeb78e6eb5d1d0d2d909f"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "bc71fba3bc2ec54805d47b58a9411abf099bcafc15751ecd82c2ce51a9174b3f"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.8.0+0/VideoCaptureWrap.v0.8.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9579fff63ac2d5fce96af4c4842ad822678be6a"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "a01345f75ed2bf09dcf3f332c31dc39109d99266621e0b157e49ef28a37f7578"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.8.0+0/VideoCaptureWrap.v0.8.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "938d2e139447f0f234927d49c9222fff70a08961"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "de7f1a54b1242702dca40d77b94c4ad5e53bc173894f7eef9b4aa3c3c90b0fd8"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.aarch64-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dff957c6737fbf4a7922f3dae4fa211b46351342"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "77bc4df6bba7e7576d5b45485849fa864b8c5616f4ea2daf0752d9ebac883363"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cc56ccb1489876251be504d3cb668476f1aca9a"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "455009177f465b81d9611c616c1815f3ec639d565e9b8f66922a5d203a640954"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.aarch64-linux-musl-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "987652e6661d25409eac4d6ff08c705cb39fc5f1"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "6758505ff320489ea2f33252a6c5ce8ca0df67d3a0600ce792c8984adbcd595f"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8865d04487543c36961631e45aa77711bac72f4e"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "2cd83895b54cbb0223109e797e735b87195641d8a1447f6cb6263f2c974d86af"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40921c73e873e7f5a0712b394aace0f0bc247afb"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "79b4f97ee1d22e0c7d0b3126000367273413c690559a4ee29a58612905dd4738"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82878685a5ee6bbe619f91188c1151d2f395a45b"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "1bd446eed968e668e1eb33e8387c0b688e4b02c17609afa407d2b31a0cb75085"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e60b0dec0f415ad02a5f4fc50fe092fae970052"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "2be7dfb140c63abaecadcd9b5fccdd9a4989fcabf7aab06a3d0f31d3ac926bef"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca20d41d8ef30bd9b847f807d106b97d2545d019"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "20a20d9ce3fe74a3c58181f78e052c5a140e10ff0f512a9645cb6ca74d199b6e"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.i686-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6f89c2a817fb4cbefedba8690818cdc9c84fb9d"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "8fbeaa50ba0cd82fe651b070d7f987093ad403a054d4215a524aafcec2eafb16"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.i686-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8174dc0bdb7a8dc2a9e621e76107db007d3adf44"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "565f3ba4fd2934bfd574980aa5179895bb292fe7925138de9622205d1aa3df4b"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.i686-w64-mingw32-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f60bca608923a12ad94da068a8f19e03822610d"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "61e947a849e1dcffe0bcc4655f7191df576cb65d9cdab672a1bb8514f9c170c1"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.i686-w64-mingw32-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
git-tree-sha1 = "9f96d87a5288d7086a9ececd16d355e818efdb3a"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "cd0df9ec51c1a9d0e0d32e696970f3b196b5dd573833b885ae710a906d92a4de"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.x86_64-apple-darwin.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8990ccba36ab7959c17af78da69c2cff54bcf9a7"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "3b63ec83732a7176512e27f5920608af1210667b41a7cb70d34685b0f454ec71"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.x86_64-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e2897e459e3c14c1a51259d9f00b999f4ff389c"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "8cce07fb79d932f7ed479c5ae8887f42e513667f54804a3369fb7f6b73f2fd6d"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39269a365d7c7f3921a5e338a5d04c5c6f69a07d"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "8d322a6e0431bc8e2df919d7b7f1e0301460ba302448a5564d3b5a3f0bd75dac"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ab57c38e4623a843862e4a0ef6ad1f0b6958a22"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "8787fd035747bde1535abf6cc9ca3a1b6fd3ff2ea6dba3f7c776d2acaedb1b21"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.0+0/VideoCaptureWrap.v0.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
