[[VideoCaptureWrap]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95fa6d4c90b16e82eda114b07c6a8660d29f838f"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "99c3b09d6c73d5830651bc5b8208d7b96bd1f71cba6e12d6ef7b1f117635ccc8"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.1+0/VideoCaptureWrap.v0.4.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
git-tree-sha1 = "2e6c26d7f08714dafdc4060c324bbbfa6cb02476"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "ce480e21e8415132909a67db4c3ccbd05f2189a41f8682f2c9ec8844713a3bc2"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.1+0/VideoCaptureWrap.v0.4.1.armv7l-linux-gnueabihf.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee1c61e90df6244f4883dd5d9722a901b621fc9f"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "a5ebf555eae1472e4d512539978d64c8c7fbb9080c268c9750bed1e81ba045f5"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.1+0/VideoCaptureWrap.v0.4.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28c5ca1f0d552a232733062d18adf988d294573c"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "47b4efbff59ce65decb2a21a1750679e6d0fe04265630b5448c165a801c5d383"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.1+0/VideoCaptureWrap.v0.4.1.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22d8703abd125e3e6d6c9c83cf14b9d6f1df1ba7"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "aa6270f43ae8b090c465435182ad436cd7dea29176b1f54c34eb6594e7f8969d"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.1+0/VideoCaptureWrap.v0.4.1.x86_64-w64-mingw32-cxx11.tar.gz"
