[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "073b2010fbf0380fb52fa4e9625882a01e6273ad"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "a23162beabd1e3b1b63f17d7af6b0203df83e5a7978c8032f5f18c20846a4369"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.5+0/VideoCaptureWrap.v0.1.5.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ddfb33449f0f38c22530ab29d9f407f41442a3f"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "497d4e01e77ae9c775e7ed3ee5f06671580c066c0b6eb989d547d660d630076a"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.5+0/VideoCaptureWrap.v0.1.5.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "408283fde918d8f95da1140443d7676c3884ae56"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "4aca369c969d2e27a5b02076482209e8c946e84fc856d2b206cbfbf790c697b0"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.5+0/VideoCaptureWrap.v0.1.5.x86_64-w64-mingw32-cxx11.tar.gz"
