[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93f3099968736defa6f86a3593b2a15e64cb7caa"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "da71de34eeed476193815b158505aafabb7fd08c5a596f0792f809be0d9f9cf6"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.3+0/VideoCaptureWrap.v0.1.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ca3f21f2b4b308e098366b4aca4334481f74b72"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "4cdae9079996d9e4c8f58004dfea70e98a386b3d87e4e8cd328e4e0e03a5ae37"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.3+0/VideoCaptureWrap.v0.1.3.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03ec647441276d9eda9644d7720a82635e5bd379"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "d7fc9a487f086b5423b6378fe7f7aafcfa7286a37e82e745f7f23b4b4382067e"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.3+0/VideoCaptureWrap.v0.1.3.x86_64-w64-mingw32-cxx11.tar.gz"
