[[VideoCaptureWrap]]
arch = "armv7l"
git-tree-sha1 = "52476f71b07988aeac2858091d50e329903d3f94"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "e6b6fb1897927eab37bc49bbabba13f82acee3e8be348feecc467db702462c01"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.2+0/VideoCaptureWrap.v0.4.2.armv7l-linux-gnueabihf.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a851cef086a820da2065179bdcec672c7e6db412"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "202a146760574173079a725e7a81478997ca72578018b80a927e0bfeee8c88cb"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.5.2+0/VideoCaptureWrap.v0.5.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0dbd642329aff8083f19ee8fb978e949f1e675a"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "70bf864c99413e9f477539464ec981cce8b7db1b5835575929540a24cd62e6fd"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.5.2+0/VideoCaptureWrap.v0.5.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4551d15a95265bb9985fe7ae42682e7767d7560d"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "29339864420731b1a2a847c689995e6cec5e91618277ab1d12773b35e5f215a0"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.5.2+0/VideoCaptureWrap.v0.5.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b80f9d0efcb469c152a3c26a36b16873250dd62b"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "099e607be2517ab01cf2d0f0d9feb23392953c4c6e2bd8b7325627fda2a810be"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.5.2+0/VideoCaptureWrap.v0.5.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "646c9cc2298a994efbff26c8689b73e88c6b3ae1"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "0cad8e37eecf9e66df899ec5050efb4c9e654ee39615449130d9e41c62ef1f7f"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.5.2+0/VideoCaptureWrap.v0.5.2.x86_64-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9956ae0a30ae9ae58e3abf91463cee055846c70c"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "301eb29c89766657d742dc5501d864099e48234bbbcfb599e1ef638d4162af0f"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.5.2+0/VideoCaptureWrap.v0.5.2.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "410c9111f2e7d5188fe2ba4f3f9689baf1d31ea3"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "bdca9f2dbb2927ea75e7a49b6fc9704dc42c43214dde37125bf342cfa1743748"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.5.2+0/VideoCaptureWrap.v0.5.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e61e567b593430c1f451b203cc0c19520cee1040"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "b59cdd7ec5d2651c64dfe5faa0f66e4ebeeb1aa973663225ba3c29a3a432d806"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.5.2+0/VideoCaptureWrap.v0.5.2.x86_64-w64-mingw32-cxx11.tar.gz"
