[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f895301c5545326b102d52c8627469f84ba08fa4"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "1fb4e8cf8428f93ce71dee84b4d75f0543ce9c185f5ef52b64c0a1eced1aa5b8"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.1+0/VideoCaptureWrap.v0.1.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e744138f1c2067521bd4190137954936843b7151"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "9f00cbb7e3eda700c5a8a8a72e39e8162395cf64f4730c82ee97700ef94fc4ed"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.1+0/VideoCaptureWrap.v0.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b524526466ef046422b28ab3b9d9d9b2876ee71b"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "beac3b48905a3008d8f5b38fb40fd0214862ffdd1860b93829d09755b1112239"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.1+0/VideoCaptureWrap.v0.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
