[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12896e1326667cccbd72dc7c77e18cd6881fe0a0"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "98d47ec2654aa56a0b7adc49259f451c209c7405e32bda40e5e9986780f4b92f"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.4+0/VideoCaptureWrap.v0.1.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a505524453241e1b4041549df4ea4bcb22697b7f"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "97dd518ac51b97ad7ddfa4538ecee1d4dceed9f4110f30fac39308bb08bd82a1"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.4+0/VideoCaptureWrap.v0.1.4.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b86414788516be88a36cd22a3ad241ac07574ae6"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "c9d93aa4b1432eaeb6598682e31421e2498ec62c03434ee9bd2cd1ec5040c733"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.1.4+0/VideoCaptureWrap.v0.1.4.x86_64-w64-mingw32-cxx11.tar.gz"
