[[VideoCaptureWrap]]
arch = "armv7l"
git-tree-sha1 = "52476f71b07988aeac2858091d50e329903d3f94"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "e6b6fb1897927eab37bc49bbabba13f82acee3e8be348feecc467db702462c01"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.2+0/VideoCaptureWrap.v0.4.2.armv7l-linux-gnueabihf.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf76fe30e38a9462e5aeeb78e6eb5d1d0d2d909f"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "bc71fba3bc2ec54805d47b58a9411abf099bcafc15751ecd82c2ce51a9174b3f"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.8.0+0/VideoCaptureWrap.v0.8.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9579fff63ac2d5fce96af4c4842ad822678be6a"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "a01345f75ed2bf09dcf3f332c31dc39109d99266621e0b157e49ef28a37f7578"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.8.0+0/VideoCaptureWrap.v0.8.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "938d2e139447f0f234927d49c9222fff70a08961"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "c586e59debf10388bbcf2c944d1e9d0fdf67c89f56c2a3dda72aed632b3a73cc"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.aarch64-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dff957c6737fbf4a7922f3dae4fa211b46351342"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "16859e72c1c4789adb6e372dcb94f0cbb834e2079eefcb423faf137f3c323f56"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.aarch64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cc56ccb1489876251be504d3cb668476f1aca9a"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "30d70b74e00aec33a87c9b7940ad694a246a024ff4c716cb59c8f7bf8f4acbe8"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.aarch64-linux-musl-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "987652e6661d25409eac4d6ff08c705cb39fc5f1"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "8ecca8e7f5b946904aab4a6be017ad20e563a30834118aabc5a9563bbc434365"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.aarch64-linux-musl-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8865d04487543c36961631e45aa77711bac72f4e"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "99c3c90fcf1da24203ea2afd8a0fc9765229546f8496ca897804c3744f9c49c5"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40921c73e873e7f5a0712b394aace0f0bc247afb"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "624e08fb02049237b9b6586e84afde50076aa135c58c4b0dd5f2e444d42bd58a"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82878685a5ee6bbe619f91188c1151d2f395a45b"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "fe6cd0c0e7bafed1b1c61e785beb4171b055bc9d40b544724dff4f893cdaca9c"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e60b0dec0f415ad02a5f4fc50fe092fae970052"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "6dd39e7d19abbbd2103b9e3305e8c1b71fd0c988e27b634601f483cc09026f57"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca20d41d8ef30bd9b847f807d106b97d2545d019"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "a8efa85462a57d8b66210ac3c701b325199c1a5029d16ff80a1103d4513ec1d7"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.i686-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6f89c2a817fb4cbefedba8690818cdc9c84fb9d"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "69660d29b17199c9107321f05e0ecd250f2c43b1f265fe0618d6de113cc9595a"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.i686-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2253683f8b63d050c2d0b347ac94cf6161450329"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "e6eab8a660dade5ad48f765d3a62c88f4078a099fdab06ef10268f1d94144eb7"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.i686-w64-mingw32-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7545c424af645b3416405600659510f275c4f5b"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "f3c3a4dab1a6683f35392f2d0683504b3539ecf4fa31d57d75220697a250d3af"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.i686-w64-mingw32-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
git-tree-sha1 = "9f96d87a5288d7086a9ececd16d355e818efdb3a"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "d0086be5fafa18eaed73ba0890d1743ce6358c979bface9defccb34b1f206568"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.x86_64-apple-darwin.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8990ccba36ab7959c17af78da69c2cff54bcf9a7"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "90d7b8f657767140a53d8506997a2ade755c27510907374bc91c3df043f12b33"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.x86_64-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e2897e459e3c14c1a51259d9f00b999f4ff389c"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "4e042025e1795ace612be7d235e83549962e535e660960682daa4f4782b57049"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "122788b2ac2f84798601ebf42bbe3de820bf3456"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "392a6e7c0545aaf79748c4ac27ee53db0bdf8c6aca2cb3a1cae4d9aaceb21157"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06f70c9cef0534eb524eb3a67a7fc3baf7c93f6f"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "bcdca72428647d665a6b423875d7e5059339bbd1bea42a0ac341fb56cbb3ce69"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.1+0/VideoCaptureWrap.v0.9.1.x86_64-w64-mingw32-cxx11.tar.gz"
