[[VideoCaptureWrap]]
arch = "armv7l"
git-tree-sha1 = "52476f71b07988aeac2858091d50e329903d3f94"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "e6b6fb1897927eab37bc49bbabba13f82acee3e8be348feecc467db702462c01"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.4.2+0/VideoCaptureWrap.v0.4.2.armv7l-linux-gnueabihf.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf76fe30e38a9462e5aeeb78e6eb5d1d0d2d909f"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "bc71fba3bc2ec54805d47b58a9411abf099bcafc15751ecd82c2ce51a9174b3f"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.8.0+0/VideoCaptureWrap.v0.8.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9579fff63ac2d5fce96af4c4842ad822678be6a"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "a01345f75ed2bf09dcf3f332c31dc39109d99266621e0b157e49ef28a37f7578"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.8.0+0/VideoCaptureWrap.v0.8.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7facb0b826182c1dbc5433110c5ace586150fbc7"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "c06694abd961675f01fa4369bcde80c3bad3c9431ccfcf78b9180ad636199a36"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.aarch64-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1abd5d4380a4459d316797462c23ede796372741"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "97a3f3331f4d9cddd84a67e4d165f6d9940f229d6c8d45f3b7ebd9392e43fc5c"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.aarch64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcedbfd4508718912cf7dfa40e72fb87c1e549fa"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "66b889cb335167cb05b5eb48cc4a809d114e5a1c3f46cd2ab47f27192e1af898"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.aarch64-linux-musl-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "634ce77ef22b914cf5feaebf4852ec0608198190"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "b9e1d23898bc03833a4586760a2eacbd9ab3f35f407b2e1ad1ba3eed8df9b170"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.aarch64-linux-musl-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a50a7f006fdcd2526b7b0e50ff6fd7b720be683f"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "6b7e489ea95ef1bd7504647574bd60c1d6e491c50503f9d91793838fcb8e1c5a"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6877cb0e709dd8107030cfae466f949834ee016e"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "b83af946fa5e3e36665449b9e61066334ddb528ad4f4dd85f2c00b0979dbb68c"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "edf92abfc5c7d20f86d23fdbee1334f0bb88ff87"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "08626c98d397a07b6878d9520a56f375f079253f4d2e6b47265c58b6aa4e36cf"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "606c26a21cff9cdfd41f444ae91b5b58ad9f2bca"
libc = "musl"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "95eeaadbbeebf6f80ad9b75d76580ad9e0ec4ed9e5cf46e2abbce0cadb7470bd"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ef7e7bdbff5b5bd72dcd10f825b66a993d7581a"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "896ef33727fee7c65c29f5a12518b8e0f45d9fb20eea81e537f041e0915c398c"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.i686-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c02a2c547170aecc3c974dbc7c5cdedab6dc4893"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "0f881c5d4887dc3ec0205f6c08186806aeef2e013453acd2c714a25174115188"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.i686-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a362e1b37b5dbe368063b05fd10e7dd29b57d92"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "ef11112ca831496ba872092f1e01d569b45ebb351dc894f903136fc1ee2ba311"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.i686-w64-mingw32-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d484297d834dd7ae69a7b763a20eb489f48c64e0"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "1da17a4070ada17b4db0986877f755a201d753446ee241293a3627356b91cb41"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.i686-w64-mingw32-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
git-tree-sha1 = "598afb53d826065829f45fa3aed891517e6d7e62"
os = "macos"

    [[VideoCaptureWrap.download]]
    sha256 = "3b9b524ca4dafeec973e7fe13eee5c188f0dc34cc16007e841b28d3275b78ee9"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.x86_64-apple-darwin.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f3de95b9096d770d2b17071006088fc71f2ff12"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "d8090ef5d4f3346f0f25eb4874070a126af25cc52fab478bc4d157ed3125e55e"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.x86_64-linux-gnu-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acaa563a16850913da88f81899cc66c43d218c17"
libc = "glibc"
os = "linux"

    [[VideoCaptureWrap.download]]
    sha256 = "cfe20d0c9b0e74ba0dc7c4271ea87e376eafc911821481e9b218295daa5818a3"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.x86_64-linux-gnu-cxx11.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b529091d661da7ea831c2b5ca5ec064fd602e804"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "8fe75a86f34caf679b8ab2687fa67ca247484beac66dad8bc81c9b2b9cc4cf57"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[VideoCaptureWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b1ad2b4f5d6ddcfe581025c14ca7b734804c1d6"
os = "windows"

    [[VideoCaptureWrap.download]]
    sha256 = "f4b81810d601cb0937b2ecf2b6ed7c26f85da5d3ac4e9c22dd9ae91cd1a2ad52"
    url = "https://github.com/terasakisatoshi/VideoCaptureWrap_jll.jl/releases/download/VideoCaptureWrap-v0.9.2+0/VideoCaptureWrap.v0.9.2.x86_64-w64-mingw32-cxx11.tar.gz"
